### ISSUE TITLE
How can I run the tests in a forked repo?

### ISSUE THREAD

**Issue by gregblass** [highfidelity/fake_braintree#105]
I forked this repo and I have the code in /lib/fake_braintree-0.7.0 (open to suggestions on where the standard place to put a forked repo in your project is. this is the first time I've done it).

I'm trying to follow the readme and the principles of TDD and run the tests, then write my test for the feature I'm adding, then add the feature.

This is what I'm trying in my root directory:

    rspec lib/fake_braintree-0.7.0/spec/fake_braintree
    /Users/gregblass/apps/myapp/lib/fake_braintree-0.7.0/spec/fake_braintree/registry_spec.rb:3:in `<top (required)>': uninitialized constant FakeBraintree::Registry (NameError)
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load'
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/bin/rspec:23:in `load'
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/bin/rspec:23:in `<main>'
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/bin/ruby_executable_hooks:15:in `eval'
	from /Users/gregblass/.rvm/gems/ruby-2.2.2@myapp/bin/ruby_executable_hooks:15:in `<main>'

What am I missing here?

**Comment by gregblass** [comment]
OK I was able to get tests running, but I'm getting 25 failing tests, all saying "expecting a gzipped response" ...

**Comment by gregblass** [comment]
Nevermind, got it working. I wish github would let me delete issues that I started...
