### ISSUE TITLE
Can't use in conjunction with WebMock

### ISSUE THREAD

**Issue by mdotterer** [highfidelity/fake_braintree#52]
We are already using WebMock for other tests and it seems to be incompatible with FakeBraintree.  I attempted to configure WebMock to allow connections on 127.0.0.1, but it seems that FakeBraintree is attempting to make a connection in the bundler require, before I get a chance to make this configuration. Is there anything that could make the two gems work in harmony?

**Comment by maxrosecollins** [comment]
I can't seem to get this working.
In my spec_helper I have
```
WebMock.disable_net_connect!(allow_localhost: true)
FakeBraintree.activate!(gateway_port: 1234)
```
I get
```
You can stub this request with the following snippet:

stub_request(:get, "http://127.0.0.1:53563/__identify__").
  with(:headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}).
  to_return(:status => 200, :body => "", :headers => {})
```

With no registered stub requests, even though I do...

And if i put the `FakeBraintree.activate!(gateway_port: 1234)` above `WebMock.disable_net_connect!(allow_localhost: true)`

Then it doesn't run any of my tests and i get the stacktrace

```
from /Users/max/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:1133:in `get'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/server.rb:56:in `block in responsive?'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/webmock-1.22.3/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/webmock-1.22.3/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/server.rb:56:in `responsive?'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-2.5.0/lib/capybara/server.rb:66:in `boot'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fake_braintree-0.8.0/lib/fake_braintree.rb:116:in `boot_server'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fake_braintree-0.8.0/lib/fake_braintree.rb:24:in `activate!'
        from /Users/max/dev/yummy-waffle/spec/spec_helper.rb:19:in `<top (required)>'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `require'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `block in requires='
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `each'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `requires='
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:108:in `each'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:21:in `configure'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:101:in `setup'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
        from /Users/max/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
        from /Users/max/.rbenv/versions/2.2.3/bin/rspec:23:in `load'
        from /Users/max/.rbenv/versions/2.2.3/bin/rspec:23:in `<main>'
```
